### ISSUE TITLE
CI test fails 

### ISSUE THREAD

**Issue by melezhik** [grondilu/openssl#16]
Hi! Here is the full report - https://ci.sparrowhub.io/report/2367

23:50:13 :: [SSL] Testing with plugin: Zef::Service::Shell::prove+{<anon|1>}
23:50:13 :: [SSL] This container does not reference a native integer
23:50:13 :: [SSL]   in sub CArray2Buf at /var/.sparrowdo/env/main/.sparrowdo/source/lib/SSL/Digest.pm (SSL::Digest) line 31
23:50:13 :: [SSL]   in sub md4 at /var/.sparrowdo/env/main/.sparrowdo/source/lib/SSL/Digest.pm (SSL::Digest) line 65
23:50:13 :: [SSL]   in sub md4 at /var/.sparrowdo/env/main/.sparrowdo/source/lib/SSL/Digest.pm (SSL::Digest) line 53
23:50:13 :: [SSL]   in block <unit> at t/basic.t line 30
23:50:13 :: [SSL] t/basic.t ... 
23:50:13 :: [SSL] 1..11
23:50:13 :: [SSL] # You planned 11 tests, but ran 0
23:50:13 :: [SSL] Dubious, test returned 255 (wstat 65280, 0xff00)
23:50:13 :: [SSL] Failed 11/11 subtests 
23:50:13 :: [SSL] This container does not reference a native integer
23:50:13 :: [SSL]   in sub CArray2Buf at /var/.sparrowdo/env/main/.sparrowdo/source/lib/SSL/Digest.pm (SSL::Digest) line 31
23:50:13 :: [SSL]   in sub md4 at /var/.sparrowdo/env/main/.sparrowdo/source/lib/SSL/Digest.pm (SSL::Digest) line 65
23:50:13 :: [SSL]   in block <unit> at t/binary.t line 30
23:50:13 :: [SSL] t/binary.t .. 
23:50:13 :: [SSL] 1..10
23:50:13 :: [SSL] # You planned 10 tests, but ran 0
23:50:13 :: [SSL] Dubious, test returned 255 (wstat 65280, 0xff00)
23:50:13 :: [SSL] Failed 10/10 subtests 
23:50:13 :: [SSL] Test Summary Report
23:50:13 :: [SSL] -------------------
23:50:13 :: [SSL] t/basic.t (Wstat: 65280 Tests: 0 Failed: 0)
23:50:13 :: [SSL]   Non-zero exit status: 255
23:50:13 :: [SSL]   Parse errors: Bad plan.  You planned 11 tests but ran 0.
23:50:13 :: [SSL] t/binary.t (Wstat: 65280 Tests: 0 Failed: 0)
23:50:13 :: [SSL]   Non-zero exit status: 255
23:50:13 :: [SSL]   Parse errors: Bad plan.  You planned 10 tests but ran 0.
23:50:13 :: [SSL] Files=2, Tests=0,  3 wallclock secs ( 0.03 usr  0.01 sys +  4.85 cusr  0.29 csys =  5.18 CPU)
23:50:13 :: [SSL] Result: FAIL
23:50:13 :: ===> Testing [FAIL]: SSL:ver<0.2.1>

HTH

**Comment by grondilu** [comment]
Well this is an old repo that is quite redundant with Digest.   Not sure I'm going to maintain it.

**Comment by melezhik** [comment]
Ok.
